// Main site
GET http://localhost:3000/
### 

GET http://localhost:3000/api
###

GET http://localhost:3000/api/test
###


///////////////////////////////////
// POSTS
//
// (CREATE post)
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "user": "639f3e69ac3730f6b47ef8b2",
  "message": "The quick brown fox jumped over the lazy dog.",
  "posted": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###

// (READ post)
GET http://localhost:3000/api/posts
###